name: success_airline
description: A new Flutter project.

publish_to: 'none'  
version: 1.3.1+14

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  get: ^4.6.0
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.0.3
  lottie: ^1.3.0
  firebase_core: ^1.17.0
  cloud_firestore: ^3.1.15
  firebase_auth: ^3.3.18
  image_picker: ^0.8.5+3
  image_picker_for_web: ^2.1.8
  firebase_storage: ^10.2.16
  uuid: ^3.0.6
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  circular_bottom_navigation: ^2.0.0
  dotted_border: ^2.0.0+2
  file_picker: ^4.5.1
  just_audio: ^0.9.20
  path_provider: ^2.0.9
  shared_preferences: ^2.0.15
  flutter_launcher_icons: ^0.9.2
  in_app_purchase: ^3.0.4
  animated: ^2.0.0
  animated_splash_screen: ^1.2.0
  cupertino_will_pop_scope: ^1.2.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svgs/
    - assets/pngs/
    - assets/json/
    - assets/fonts/

  
  fonts:
    - family: avenir
      fonts:
        - asset: assets/fonts/Avenir-55-Roman.otf
        - asset: assets/fonts/Avenir-95-Black.otf
        - weight: 700
